version: '3.8'
services:
  mysql:
    image: mysql:8.0.28-oracle
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --lower_case_table_names=1 --collation-server=utf8mb4_unicode_ci --skip-name-resolve  #覆盖容器启动后默认执行的启动mysql命令
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /env/docker/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /env/docker/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /env/docker/mysql/log:/var/log/mysql #日志文件挂载
    expose:
      - 3306
  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - /env/docker/redis/data:/data
      - /env/docker/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
  nginx-server:
    image: nginx:1.21
#    restart: always
    container_name: nginx-server
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
    volumes:
      - /env/docker/nginx/html:/usr/share/nginx/html
      - /env/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /env/docker/nginx/logs:/var/log/nginx
  